# Generated by Django 5.2.7 on 2025-12-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_alter_productos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
