# Generated by Django 5.2.7 on 2025-12-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productos_imagen1_productos_imagen2_productos_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='imagen1',
            new_name='imagen_dos',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='imagen2',
            new_name='imagen_uno',
        ),
        migrations.AlterField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
