# Generated by Django 5.2.7 on 2025-12-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('trabajador', 'Trabajador'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
